apiVersion: apps/v1
kind: Deployment
metadata:
  name: uniunity
  labels:
    app: uniunity
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: uniunity
  template:
    metadata:
      labels:
        app: uniunity
        tier: uniunity
    spec:
      containers:
      - name: uniunity
        image: choiaerim/uniunity:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: uniunity
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PW
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: uniunity
  labels:
    app: uniunity
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: uniunity
    tier: uniunity
  type: LoadBalancer
