apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: MzQuNjQuMTg1LjIxOA==
  DB_USER: cm9vdA==
  DB_PW: bXlwYXNzd29yZA==
  DB_PORT: MzMwNg==
  DB_NAME: dW5pdW5pdHlEQg==
